### ISSUE TITLE
Question about the similarity function used while training

### ISSUE THREAD

**Issue by YAOYI626** [KunpengLi1994/VSRN#12]
Hi KunPeng,

Appreciate for your excellent paper and code. I noticed that you state your similarity function as **inner product** in eq.(8)'s caption in your paper. But I find there is two similarity function setting in your code: measure ”order“ for **subtraction function** and measure "cos" for measure **cosine similarity function**, [this line](https://github.com/KunpengLi1994/VSRN/blob/8ae62a02d3b6f2edb781d5a8f1e7abf17aa47f78/model.py#L359). So did your only use the **inner product** for testing? Or because the code you upload is not the final version？Cause my results with your code could not achieve that is stated in your paper.

Thanks a lot for your coming reply.

**Comment by KunpengLi1994** [comment]
Hi,

For this part, we simply follow VSE++ and keep the default setting as [this line](https://github.com/KunpengLi1994/VSRN/blob/master/train.py#L68), which is implemented by inner product as shown [here](https://github.com/KunpengLi1994/VSRN/blob/master/model.py#L339).  

To reproduce the results, please check the environment settings such as using Python 2.7 and Pytorch 0.4. You can also refer to issue #11 and issue #5 .

**Comment by YAOYI626** [comment]
Hi KunPeng,

Thanks a lot. The "cosine" [here](https://github.com/KunpengLi1994/VSRN/blob/master/train.py#L68) misleads me.  

And it seems that the version of PyTorch do have a big impact on the results, strange as it is, it is. I will close this issue.
