### ISSUE TITLE
Two evaluated model

### ISSUE THREAD

**Issue by DeepRunner** [KunpengLi1994/VSRN#13]
Hi.
There seems exactly single training setting in your model(unlike two settings i.e. i2t-attention/t2i-attention in SCAN ).  

1) How are these 2 model trained, just 2 runs with identical setting?
2) How are these 2 model selected on val data? Ensemble two model first and then select the best, or select dependently and then ensemble?
3)Why 2 models, for fair comparison with SCAN?

**Comment by DeepRunner** [comment]
Sorry, I saw the similar issues.
But I still wonder that
1) How are these 2 model selected on val data? Ensemble two model first and then select the best, or select dependently and then ensemble?
2) How are these 2 model trained, just 2 runs with identical setting?

**Comment by KunpengLi1994** [comment]
Hi,

Thanks for your good questions!
1. We trained these two models separately. But I think your thought of doing ensemble at the training procedure may lead to better results.  

2. Just run with the same setting. We did not try making training settings different and just rely on randomness at the training procedure.
