### ISSUE TITLE
The result cannot be reproduced 

### ISSUE THREAD

**Issue by haoopan** [KunpengLi1994/VSRN#23]
Thanks for your open-sourcing!
When I run this code, the results I got are not as good as those given in your paper. This is the result on flickr30k using VSRN. My environment is python3.6 and pytorch1.2.0. What should I do to get the results on the paper? My result are here:
rsum: 453.9
Average i2t Recall: 81.9
Image to text: 65.3 87.8 92.5 1.0 5.1
Average t2i Recall: 69.4
Text to image: 49.1 75.8 83.4 2.0 13.3

**Comment by KunpengLi1994** [comment]
Hi, thanks for your interest in our work. Our code is based on the code base of VSE++, which is for python 2.7 and pytorch 4.0. We clearly stated these requirements in the readme. Please consider follow such requirements especially python version. 

Please also refer to details in existing issues and discussions, e.g. https://github.com/KunpengLi1994/VSRN/issues/15
