### ISSUE TITLE
encoder_hidden

### ISSUE THREAD

**Issue by kywen1119** [KunpengLi1994/VSRN#3]
I notice that the you refer to the dimension of "encoder_hidden" in your code DecoderRNN.py as (num_layers * num_directions, batch_size, dim_hidden). However, if it's extracted by GRU, the dimension of hidden_state should be (num_layers * num_directions, seq_len, dim_hidden). This confuses me when trying to run your codes.

**Comment by KunpengLi1994** [comment]
It is obtained from this [line](https://github.com/KunpengLi1994/VSRN/blob/master/models/EncoderRNN.py#L57) of the Encoder. If you check the Pytorch GRU code, "hidden" actually represents the hidden state for the last time step not for all time steps.
