### ISSUE TITLE
How to visualize attention?

### ISSUE THREAD

**Issue by czhxiaohuihui** [KunpengLi1994/VSRN#4]
Could you share how to visualize the attention?  Vey very Thanks!

**Comment by KunpengLi1994** [comment]
Hi,

You can find detailed descriptions about attention visualization in Section 4.5 about Attention visualization of the final image representation. 

Basically, we calculate the inner product similarity (same as in Eq. 8) between each region feature V^∗ and the final whole image representation I . Then we rank the image regions V^∗ in the descending order of their correlation with I and assign a score s_i to each v∗i according to its rank r_i. The score is calculate by s_i = λ(k− r_attn)^2 , where k is the total number of regions, λ is a parameter used to emphasize the high ranked regions. We set λ = 50 in our experiments. Then for the final attention map (similarity map), the attention score at each pixel location is obtained by adding up scores of all regions it belongs to.

**Comment by MI-WENYU** [comment]
> 
Hello, thank you for your great work. I did not find the code of attention visualization in the code you provided, may I ask where it is?
