### ISSUE TITLE
when evaluate, something about models

### ISSUE THREAD

**Issue by IRIS00123** [KunpengLi1994/VSRN#5]
def evalrank(model_path, model_path2, data_path=None, split='dev', fold5=False):
 
there are two models, but when train, save only one model.
what are the two models?
Thank you very much !

**Comment by KunpengLi1994** [comment]
Hi, 

Thanks for your question. As stated in Section 4.3 of the paper, we follow recent state-of-the-art method SCAN to report results by combing scores of two trained models. In our case, you can train two times to get two models.

**Comment by IRIS00123** [comment]
hello, thanks for your answer. i have a new question. 


        fc_img_emd = self.fc(images)
        fc_img_emd = l2norm(fc_img_emd)
        # GCN reasoning
        # -> B,C,n
        GCN_img_emd = fc_img_emd.permute(0, 2, 1)
        GCN_img_emd = self.Rs_GCN_1(GCN_img_emd)
        GCN_img_emd = self.Rs_GCN_2(GCN_img_emd)
        GCN_img_emd = self.Rs_GCN_3(GCN_img_emd)
        GCN_img_emd = self.Rs_GCN_4(GCN_img_emd)
        # -> B,n,C
        GCN_img_emd = GCN_img_emd.permute(0, 2, 1)
        GCN_img_emd = l2norm(GCN_img_emd)
        rnn_img, hidden_state = self.img_rnn(GCN_img_emd)
### 
**the code has no code for obtaining semantic relationship**
